language: objective-c
cache: cocoapods
osx_image: xcode7.2

before_script:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - export LANG=en_US.UTF-8
script: xctool -workspace JGORegExpBuilder.xcworkspace -scheme JGORegExpBuilder build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
